name: renovate-config

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/renovate-config.yaml
      - default.json
  push:
    branches: [main]
    paths:
      - .github/workflows/renovate-config.yaml
      - default.json

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rinchsan/renovate-config-validator@v0.0.8
        with:
          pattern: default.json
